# Generated by Django 6.0.1 on 2026-02-06 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_comment_author_alter_post_author_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='title',
        ),
    ]
